# Generated by Django 5.2.14 on 2026-05-29 05:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="메시지 UUID",
                    ),
                ),
                (
                    "chat_model",
                    models.CharField(
                        default="rag-bge-m3",
                        max_length=100,
                        verbose_name="채팅 모델(RAG모델)",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="사용자명"
                    ),
                ),
                ("question", models.TextField(verbose_name="사용자 질문")),
                ("answer", models.TextField(blank=True, verbose_name="AI 답변")),
                (
                    "input_tokens",
                    models.PositiveIntegerField(default=0, verbose_name="입력 토큰"),
                ),
                (
                    "output_tokens",
                    models.PositiveIntegerField(default=0, verbose_name="출력 토큰"),
                ),
                (
                    "total_tokens",
                    models.PositiveIntegerField(
                        default=0, verbose_name="사용 토큰(합계)"
                    ),
                ),
                (
                    "response_ms",
                    models.PositiveIntegerField(
                        default=0, verbose_name="응답 시간(ms)"
                    ),
                ),
                (
                    "rag_sources",
                    models.JSONField(
                        blank=True, default=list, verbose_name="RAG 참조 문서"
                    ),
                ),
                (
                    "is_error",
                    models.BooleanField(default=False, verbose_name="오류 여부"),
                ),
                (
                    "client_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="생성 IP"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_messages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "채팅 메시지",
                "verbose_name_plural": "채팅 메시지",
                "db_table": "chat_message",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        choices=[("good", "좋아요"), ("bad", "나빠요")],
                        max_length=10,
                        verbose_name="평점",
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="코멘트")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "message",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="chatbot.chatmessage",
                        verbose_name="메시지",
                    ),
                ),
            ],
            options={
                "verbose_name": "채팅 피드백",
                "verbose_name_plural": "채팅 피드백",
                "db_table": "chat_feedback",
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="세션 UUID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="사용자명"
                    ),
                ),
                (
                    "chat_model",
                    models.CharField(
                        default="rag-bge-m3", max_length=100, verbose_name="채팅 모델"
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="제목"),
                ),
                (
                    "client_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="접속 IP"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "채팅 세션",
                "verbose_name_plural": "채팅 세션",
                "db_table": "chat_session",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="chatbot.chatsession",
                verbose_name="세션",
            ),
        ),
    ]
