# Generated by Django 5.2.14 on 2026-05-29 05:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_loginlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RagConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rag_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="RAG UUID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="RAG명")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "대기 중"),
                            ("processing", "처리 중"),
                            ("ready", "준비 완료"),
                            ("error", "오류"),
                            ("disabled", "비활성"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                (
                    "source_file_path",
                    models.CharField(max_length=1000, verbose_name="원본 파일 경로"),
                ),
                (
                    "source_file_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="원본 파일명"
                    ),
                ),
                (
                    "source_file_size",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="파일 크기(bytes)"
                    ),
                ),
                (
                    "source_file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("docx", "Word(docx)"),
                            ("txt", "Text"),
                            ("md", "Markdown"),
                            ("csv", "CSV"),
                            ("xlsx", "Excel"),
                            ("html", "HTML"),
                            ("other", "기타"),
                        ],
                        default="other",
                        max_length=10,
                        verbose_name="파일 유형",
                    ),
                ),
                (
                    "result_file_path",
                    models.CharField(
                        blank=True, max_length=1000, verbose_name="RAG 결과 파일 경로"
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        default="BAAI/bge-m3",
                        max_length=100,
                        verbose_name="임베딩 모델",
                    ),
                ),
                (
                    "llm_model",
                    models.CharField(
                        default="claude-sonnet-4-6",
                        max_length=100,
                        verbose_name="LLM 모델",
                    ),
                ),
                (
                    "chunk_size",
                    models.PositiveIntegerField(default=512, verbose_name="청크 크기"),
                ),
                (
                    "chunk_overlap",
                    models.PositiveIntegerField(default=50, verbose_name="청크 오버랩"),
                ),
                (
                    "top_k",
                    models.PositiveIntegerField(default=5, verbose_name="검색 Top-K"),
                ),
                (
                    "chunk_count",
                    models.PositiveIntegerField(default=0, verbose_name="청크 수"),
                ),
                (
                    "total_tokens",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="총 토큰 수"
                    ),
                ),
                (
                    "build_time_ms",
                    models.PositiveIntegerField(
                        default=0, verbose_name="빌드 소요 시간(ms)"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="오류 메시지"),
                ),
                (
                    "client_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="생성 IP"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="활성 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일시"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일시"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rag_configs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성자",
                    ),
                ),
            ],
            options={
                "verbose_name": "RAG 설정",
                "verbose_name_plural": "RAG 설정",
                "db_table": "rag_config",
                "ordering": ["-created_at"],
            },
        ),
    ]
