# Generated by Django 5.2.14 on 2026-05-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0003_ragconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ragconfig",
            name="llm_model",
            field=models.CharField(
                default="gemini-2.5-flash", max_length=100, verbose_name="LLM 모델"
            ),
        ),
    ]
