# Generated by Django 5.2.15 on 2026-06-29 02:23

import api.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "nickname",
                    models.CharField(blank=True, max_length=50, verbose_name="닉네임"),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=api.models.upload_to_date_path,
                        verbose_name="프로필 이미지",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="가입일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자",
                "verbose_name_plural": "사용자 목록",
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="GeneratedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt_kr", models.TextField(verbose_name="입력 묘사 (한국어)")),
                (
                    "prompt_en",
                    models.TextField(
                        blank=True, verbose_name="변환 프롬프트 (영문, Gemini 생성)"
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("animation", "애니메이션"),
                            ("free", "자유롭게"),
                            ("short_cut", "짧은컷"),
                            ("realistic", "사실적"),
                            ("sketch", "스케치"),
                        ],
                        max_length=20,
                        verbose_name="스타일",
                    ),
                ),
                (
                    "ratio",
                    models.CharField(
                        choices=[
                            ("1:1", "1:1 정방형"),
                            ("3:4", "3:4 세로형"),
                            ("4:3", "4:3 가로형"),
                        ],
                        default="3:4",
                        max_length=10,
                        verbose_name="비율",
                    ),
                ),
                (
                    "reference_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=api.models.upload_to_date_path,
                        verbose_name="참조 이미지",
                    ),
                ),
                (
                    "result_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=api.models.upload_to_date_path,
                        verbose_name="생성 결과 이미지",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "생성 중"),
                            ("completed", "완료"),
                            ("failed", "실패"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="생성 상태",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="오류 메시지"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성 요청일"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_images",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="생성 사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 생성 이미지",
                "verbose_name_plural": "AI 생성 이미지 목록",
                "db_table": "generated_images",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Webtoon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="제목")),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("romance", "로맨스"),
                            ("action", "액션"),
                            ("fantasy", "판타지"),
                            ("comedy", "개그"),
                            ("horror", "공포"),
                            ("drama", "드라마"),
                            ("daily", "일상"),
                            ("sports", "스포츠"),
                            ("etc", "기타"),
                        ],
                        default="etc",
                        max_length=20,
                        verbose_name="장르",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="작품 설명")),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=api.models.upload_to_date_path,
                        verbose_name="커버 이미지",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "초안"),
                            ("ongoing", "연재 중"),
                            ("completed", "완결"),
                            ("hiatus", "휴재"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="연재 상태",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webtoons",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="작가",
                    ),
                ),
            ],
            options={
                "verbose_name": "웹툰",
                "verbose_name_plural": "웹툰 목록",
                "db_table": "webtoons",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WebtoonEpisode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "episode_number",
                    models.PositiveIntegerField(verbose_name="회차 번호"),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="에피소드 제목"),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=api.models.upload_to_date_path,
                        verbose_name="썸네일",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="발행 여부"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="발행일"),
                ),
                (
                    "webtoon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        to="api.webtoon",
                        verbose_name="웹툰",
                    ),
                ),
            ],
            options={
                "verbose_name": "에피소드",
                "verbose_name_plural": "에피소드 목록",
                "db_table": "webtoon_episodes",
                "ordering": ["episode_number"],
                "unique_together": {("webtoon", "episode_number")},
            },
        ),
        migrations.CreateModel(
            name="WebtoonCut",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(verbose_name="순서")),
                (
                    "image",
                    models.ImageField(
                        upload_to=api.models.upload_to_date_path,
                        verbose_name="컷 이미지",
                    ),
                ),
                ("caption", models.TextField(blank=True, verbose_name="대사/캡션")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "episode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cuts",
                        to="api.webtoonepisode",
                        verbose_name="에피소드",
                    ),
                ),
            ],
            options={
                "verbose_name": "웹툰 컷",
                "verbose_name_plural": "웹툰 컷 목록",
                "db_table": "webtoon_cuts",
                "ordering": ["order"],
            },
        ),
    ]
