# Generated by Django 5.2.15 on 2026-06-29 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="webtooncut",
            name="metadata",
            field=models.JSONField(
                blank=True, null=True, verbose_name="편집 메타데이터"
            ),
        ),
    ]
