# Generated by Django 5.2.15 on 2026-06-29 07:58

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_add_metadata_to_webtoon_cut"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webtoon",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=api.models.upload_webtoon_cover,
                verbose_name="커버 이미지",
            ),
        ),
    ]
